In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from sklearn import tree, preprocessing

In [12]:
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"

In [13]:
train = pd.read_csv(train_url)

In [14]:
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"

In [15]:
test = pd.read_csv(test_url)

In [16]:
print(train.head())

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [17]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [18]:
train["Pclass"].value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

In [19]:
train["Survived"].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [20]:
print(train["Survived"].value_counts(normalize = True))

0    0.616162
1    0.383838
Name: Survived, dtype: float64


In [21]:
print(train["Survived"][train["Sex"] == 'male'].value_counts(normalize = True))

0    0.811092
1    0.188908
Name: Survived, dtype: float64


In [22]:
print(train["Survived"][train["Sex"] == 'female'].value_counts(normalize = True))

1    0.742038
0    0.257962
Name: Survived, dtype: float64


In [23]:
train["Sex"].value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [24]:
print(train)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25          

In [25]:
train["Age"] = train["Age"].fillna(train["Age"].median())

In [26]:
#Create the target and features of numpy arrays: target, features_one
target = train["Survived"].values

In [27]:
#preprocess
encoded_sex = preprocessing.LabelEncoder()

In [29]:
#Convert into numbers
train.Sex = encoded_sex.fit_transform(train.Sex)
features_one = train[["Pclass", "Sex", "Age", "Fare"]].values

In [30]:
my_tree_one = tree.DecisionTreeClassifier()

In [31]:
my_tree_one = my_tree_one.fit(features_one, target)

In [35]:
print(my_tree_one.feature_importances_)

[0.12231561 0.31274009 0.23491496 0.33002934]


In [36]:
#To Find mean accuracy
print(my_tree_one.score(features_one,target))

0.9775533108866442


In [38]:
test["Fare"] = test["Fare"].fillna(test["Fare"].median())

In [39]:
test["Age"] = test["Age"].fillna(test["Age"].median())

In [40]:
test_encoded_sex = preprocessing.LabelEncoder()

In [41]:
test.Sex = test_encoded_sex.fit_transform(test.Sex)

In [42]:
test_features =test[["Pclass", "Sex", "Age", "Fare"]].values

In [43]:
print('These are the features:\n')
print(test_features)

These are the features:

[[ 3.      1.     34.5     7.8292]
 [ 3.      0.     47.      7.    ]
 [ 2.      1.     62.      9.6875]
 ...
 [ 3.      1.     38.5     7.25  ]
 [ 3.      1.     27.      8.05  ]
 [ 3.      1.     27.     22.3583]]


In [45]:
my_prediction = my_tree_one.predict(test_features)
print("This is the prediction:\n")
print(my_prediction)

This is the prediction:

[0 0 1 1 1 0 0 0 1 0 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1 1 1 0 0 0 1 0 1 0 0
 0 0 1 0 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 0 1 0 0 1 1 0 1 0
 1 0 0 1 0 1 1 0 0 0 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 0 1 0 0 0 1 0 0 0 1 0 0
 0 1 1 1 0 1 1 0 1 1 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0
 1 0 1 0 0 1 0 0 1 1 0 1 1 1 1 1 0 1 1 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0 1 0
 1 1 1 0 0 1 0 0 0 1 0 0 1 0 0 1 1 1 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 1 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 1
 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 1 0
 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0
 0 1 1 1 1 0 0 1 0 0 0]


In [46]:
PassengerID= np.array(test["PassengerId"].astype(int))

In [48]:
my_solution = pd.DataFrame(my_prediction, PassengerID, columns = ["Survived"])
print("This is my solution in toto:\n")
print(my_solution)

This is my solution in toto:

      Survived
892          0
893          0
894          1
895          1
896          1
897          0
898          0
899          0
900          1
901          0
902          0
903          0
904          1
905          1
906          1
907          1
908          0
909          1
910          1
911          0
912          0
913          1
914          1
915          1
916          1
917          0
918          1
919          1
920          1
921          0
...        ...
1280         0
1281         0
1282         0
1283         1
1284         0
1285         0
1286         0
1287         1
1288         0
1289         1
1290         0
1291         0
1292         1
1293         0
1294         1
1295         1
1296         0
1297         0
1298         0
1299         0
1300         1
1301         1
1302         1
1303         1
1304         0
1305         0
1306         1
1307         0
1308         0
1309         0

[418 rows x 1 columns]


In [49]:
print("This is the solution shape:\n")
print(my_solution.shape)

This is the solution shape:

(418, 1)


In [53]:
my_solution.to_csv("my_solution_one.csv", index_label = ["PassengerID"])